# -*- coding: utf-8 -*-
"""Nifty50

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjoYoGL4AnjASHyGfy81QJE12eVtbQzD
"""

pip install yfinance

import requests
import time
from datetime import datetime
import pytz
import yfinance as yf

# Your Telegram bot token and chat ID
telegram_token = "8126533858:AAFaJ9gyw3O43-zdHxU1KrpKmEVTSTI1kxI"
telegram_chat_id = "6136185298"

# Function to send a message via Telegram
def send_telegram_message(message, telegram_token, telegram_chat_id):
    url = f"https://api.telegram.org/bot{telegram_token}/sendMessage"
    params = {
        'chat_id': telegram_chat_id,
        'text': message
    }
    response = requests.get(url, params=params)

    if response.status_code == 200:
        print("Message sent successfully")
    else:
        print(f"Failed to send message. Status code: {response.status_code}, Response: {response.text}")

# Function to get the current value of Nifty 50
def get_nifty_value():
    ticker = '^NSEI'  # Yahoo Finance ticker for Nifty 50
    try:
        nifty = yf.Ticker(ticker)
        nifty_data = nifty.history(period='1d')
        current_price = nifty_data['Close'].iloc[-1]
        return f"Nifty 50 Current Value: {current_price}"
    except Exception as e:
        return f"Error fetching Nifty value: {e}"

# Function to check if the Nifty market is open
def is_market_open():
    # Define the time zone for India
    ist = pytz.timezone('Asia/Kolkata')

    # Get the current time in IST
    now = datetime.now(ist)

    # Define market open and close times
    market_open = now.replace(hour=9, minute=15, second=0, microsecond=0)
    market_close = now.replace(hour=15, minute=30, second=0, microsecond=0)

    # Check if current time is within market hours
    return market_open <= now <= market_close

# Loop to get the Nifty value every 5 minutes at the exact minute intervals
def track_nifty_value():
    market_closed_msg_sent = False  # Flag to track if market closed message was sent
    while True:
        # Get the current time in IST
        ist = pytz.timezone('Asia/Kolkata')
        now = datetime.now(ist)

        if is_market_open():
            # Send message only when the minutes are a multiple of 5 (e.g., 9:15, 9:20, etc.)
            if now.minute % 5 == 0 and now.second == 0:
                nifty_value = get_nifty_value()
                message = f"Result: {nifty_value}"

                # Send the Nifty value to Telegram
                send_telegram_message(message, telegram_token, telegram_chat_id)
                print(message)

                # Sleep for 60 seconds to avoid sending multiple messages within the same minute
                time.sleep(60)

            market_closed_msg_sent = False  # Reset flag when market is open

        else:
            if not market_closed_msg_sent:
                # Send a single message indicating the market is closed
                send_telegram_message("Today, the market is closed.", telegram_token, telegram_chat_id)
                market_closed_msg_sent = True  # Set flag to avoid multiple messages
                print("Market is closed. Waiting for it to open...")

        # Wait for 1 second before checking again
        time.sleep(1)

if __name__ == '__main__':
    track_nifty_value()